
spring:
  server:
    port: 8080
  application:
    name: ku
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.22.92.14:3306/ku
    username: test
    password: test
    hikari:
      maximum-pool-size: 20

